# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Plains Cree spellchecker"
crk = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Plains Cree, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
crk = "TRANSLATE: A spellchecker for Plains Cree, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.crk"

[windows]
system_product_code = "{C39EDF85-3F33-47DE-B264-807512920BB9}_is1"
legacy_product_codes = [
    { value = "55A81174-4234-4E81-9EFE-88175952CD70", kind = "nsis" },
    { value = "A9726CC0-EB2D-4C93-B2F1-9EA8276F3818", kind = "nsis" }
]
[package.speller]
name = "Plains Cree"
version = "0.1.1"

[package.grammar]
name = "Plains Cree"
version = "0.1.0"

[package.tts-text-proc]
name = "Plains Cree"
version = "0.1.0"

[package.hyphenator]
name = "Plains Cree"
version = "0.1.0"
